default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kedr_db
  username: qna_user
  password: Qwerty12

test:
  <<: *default
  database: kedr_dbtest
  username: qna_user
  password: Qwerty12

production:
  <<: *default
  database: zk_site_db
  username: postgres
  password: lip.yAr.bd